// Located board pages per jurisdiction (census enumeration output).
//
// Every URL here appeared in official-domain search results during the
// enumeration research pass (2026-07-03) — none are constructed or guessed.
// All were confirmed via search index only (direct fetches blocked by the
// research environment); the production census probe re-verifies each with a
// live fetch before rung assignment. Durability note: file-path PDF URLs
// (AR, DC, GA, HI, …) churn when boards re-upload documents — where a parent
// HTML page exists it is noted, and the probe should treat PDF 404s as
// "relocate via parent page", not "requirement gone".
//
// `processing: null` means no published processing-times page was found —
// per PRD §9.3.2 those jurisdictions serve wait times as labeled estimates
// (rung E) until an official channel emerges.

export interface LocatedPage {
  url: string;
  note?: string;
}

export interface BoardPages {
  boardName: string;
  boardUrl: string;
  /** Fee schedule page, or where fees are stated. Null = only inside application system/PDFs. */
  fees: LocatedPage | null;
  /** Initial licensure (by examination) application instructions. */
  application: LocatedPage | null;
  /** Endorsement application instructions. Null = same page as initial. */
  endorsement: LocatedPage | null;
  /** Published processing times. Null = not published (rung E for wait_time). */
  processing: LocatedPage | null;
  confidence: 'high' | 'medium' | 'low';
  notes?: string;
  locatedAt: string; // ISO date of the enumeration research pass
}

const LOCATED_AT = '2026-07-03';

export const BOARD_PAGES: Record<string, BoardPages> = {
  al: {
    boardName: 'Alabama Board of Physical Therapy',
    boardUrl: 'https://pt.alabama.gov/',
    fees: { url: 'https://pt.alabama.gov/licensees/fee-schedule/', note: 'Dedicated fee schedule page' },
    application: { url: 'https://pt.alabama.gov/licensees/licensing-requirements/', note: 'Covers exam path incl. AL jurisprudence exam and fingerprinting' },
    endorsement: null,
    processing: null,
    confidence: 'high',
    notes: 'Standalone PT board',
    locatedAt: LOCATED_AT,
  },
  ak: {
    boardName: 'Alaska Board of Physical Therapy and Occupational Therapy (Div. of Corporations, Business and Professional Licensing)',
    boardUrl: 'https://www.commerce.alaska.gov/web/cbpl/ProfessionalLicensing/PhysicalTherapyOccupationalTherapy',
    fees: { url: 'https://www.commerce.alaska.gov/web/cbpl/ProfessionalLicensing/PhysicalTherapyOccupationalTherapy/ApplicationsForms.aspx', note: 'No standalone fee page; fees inside application forms, set by 12 AAC 02.320' },
    application: { url: 'https://www.commerce.alaska.gov/web/cbpl/ProfessionalLicensing/PhysicalTherapyOccupationalTherapy/ApplicationsForms.aspx', note: 'Online filing via MyAlaska' },
    endorsement: { url: 'https://www.commerce.alaska.gov/web/Portals/5/pub/phy4916.pdf', note: "Alaska calls endorsement 'by Credentials'; PDF application" },
    processing: { url: 'https://www.commerce.alaska.gov/web/cbpl/ProfessionalLicensing/PhysicalTherapyOccupationalTherapy/FrequentlyAskedQuestions', note: 'FAQ indicates ~8 weeks for licensure; not a formal dashboard' },
    confidence: 'medium',
    notes: 'PT and OT share one board under an umbrella licensing division',
    locatedAt: LOCATED_AT,
  },
  az: {
    boardName: 'Arizona State Board of Physical Therapy',
    boardUrl: 'https://ptboard.az.gov/',
    fees: { url: 'https://ptboard.az.gov/resources/new-applicants', note: 'No standalone fee page; $260 application incl. endorsement stated on New Applicants page' },
    application: { url: 'https://ptboard.az.gov/resources/new-applicants', note: 'Online applications via Thentia portal' },
    endorsement: null,
    processing: null,
    confidence: 'high',
    notes: 'Standalone PT board; board FAQ may state timelines but no dedicated page found',
    locatedAt: LOCATED_AT,
  },
  ar: {
    boardName: 'Arkansas State Board of Physical Therapy (under Arkansas Department of Health)',
    boardUrl: 'https://healthy.arkansas.gov/boards-commissions/boards/physical-therapy-arkansas-state-board/',
    fees: { url: 'https://healthy.arkansas.gov/wp-content/uploads/Exam-App-and-Instructions-PT-1292.pdf', note: 'Fees inside application instruction PDFs ($100 application per indexed content)' },
    application: { url: 'https://healthy.arkansas.gov/wp-content/uploads/Exam-App-and-Instructions-PT-1292.pdf', note: 'Online filing at ar.accessgov.com/asbpt' },
    endorsement: { url: 'https://healthy.arkansas.gov/wp-content/uploads/Reciprocity-App-and-Instructions-PT-12925.pdf', note: "Arkansas calls endorsement 'reciprocity'" },
    processing: null,
    confidence: 'medium',
    notes: 'Health-department model; PDF URLs churn — parent board page is the durable anchor',
    locatedAt: LOCATED_AT,
  },
  co: {
    boardName: 'Colorado State Physical Therapy Board (DORA Division of Professions and Occupations)',
    boardUrl: 'https://dpo.colorado.gov/PhysicalTherapy',
    fees: null, // fees display only inside DPO Online Services at application time
    application: { url: 'https://dpo.colorado.gov/PhysicalTherapy/Applications', note: 'Fees/instructions shown inside DPO Online Services application system' },
    endorsement: null,
    processing: null,
    confidence: 'medium',
    notes: 'Professional-licensing-division model (DORA); no public fee schedule page found',
    locatedAt: LOCATED_AT,
  },
  ct: {
    boardName: 'Connecticut Department of Public Health — Physical Therapist Licensure',
    boardUrl: 'https://portal.ct.gov/dph/practitioner-licensing--investigations/physicaltherapist',
    fees: { url: 'https://portal.ct.gov/dph/practitioner-licensing--investigations/physicaltherapist/physical-therapist-licensure', note: '$285 application fee stated on licensure page; no standalone fee schedule' },
    application: { url: 'https://portal.ct.gov/dph/practitioner-licensing--investigations/physicaltherapist/physical-therapist-licensure', note: 'Online-only via CT eLicense' },
    endorsement: null,
    processing: null,
    confidence: 'high',
    notes: 'Umbrella health-department model; no independent PT board administers licensing',
    locatedAt: LOCATED_AT,
  },
  de: {
    boardName: 'Delaware Examining Board of Physical Therapists and Athletic Trainers (Division of Professional Regulation)',
    boardUrl: 'https://dpr.delaware.gov/boards/physicaltherapy/',
    fees: { url: 'https://dpr.delaware.gov/boards/physicaltherapy/fees/', note: 'Dedicated fee page; ~$173 PT application per indexed content; paid via DELPROS' },
    application: { url: 'https://dpr.delaware.gov/boards/physicaltherapy/newtherapist/', note: 'Covers exam and reciprocity paths; filed through DELPROS' },
    endorsement: null,
    processing: null,
    confidence: 'high',
    notes: 'Board also regulates athletic trainers; complete applications reviewed by next board meeting',
    locatedAt: LOCATED_AT,
  },
  dc: {
    boardName: 'District of Columbia Board of Physical Therapy (DC Health HRLA)',
    boardUrl: 'https://dchealth.dc.gov/service/physical-therapy-licensing',
    fees: { url: 'https://dchealth.dc.gov/service/physical-therapy-licensing', note: 'No standalone fee page; renewal $179 + $50 background check stated on licensing page; application fees inside package documents' },
    application: { url: 'https://dchealth.dc.gov/service/physical-therapy-initial-license-application-package', note: 'Online-only since June 2021' },
    endorsement: { url: 'https://dchealth.dc.gov/sites/default/files/dc/sites/doh/service_content/attachments/NEW%20PHYSICAL%20THERAPIST%20Checklist_ENDORSEMENT_.pdf', note: 'Endorsement checklist PDF — attachment URLs churn; parent page is the durable anchor' },
    processing: null,
    confidence: 'medium',
    notes: 'Umbrella health-department model; status via hotline/online check only',
    locatedAt: LOCATED_AT,
  },
  ga: {
    boardName: 'Georgia State Board of Physical Therapy (Secretary of State, Professional Licensing Boards Division)',
    boardUrl: 'https://sos.ga.gov/georgia-state-board-physical-therapy',
    fees: { url: 'https://sos.ga.gov/sites/default/files/forms/15%20Reference%20-%20Fee%20Schedule.pdf', note: 'Official fee schedule PDF ($75 application + processing fee); PDF URLs churn' },
    application: { url: 'https://sos.ga.gov/how-to-guide/how-guide-physical-therapist-and-physical-therapist-assistant', note: 'How-to guide covers exam and endorsement; GOALS portal, paper not accepted' },
    endorsement: null,
    processing: null,
    confidence: 'high',
    notes: 'Secretary-of-State licensing-division model',
    locatedAt: LOCATED_AT,
  },
  hi: {
    boardName: 'Hawaii Board of Physical Therapy (DCCA Professional and Vocational Licensing Division)',
    boardUrl: 'https://cca.hawaii.gov/pvl/boards/physicaltherapy/',
    fees: { url: 'https://cca.hawaii.gov/pvl/boards/physicaltherapy/application_publications/', note: "Forms page bundles 'Requirements, Fees and Instructions'; fees inside application PDFs" },
    application: { url: 'https://cca.hawaii.gov/pvl/boards/physicaltherapy/application_publications/', note: 'Exam deadlines on separate application-deadline page' },
    endorsement: null,
    processing: null,
    confidence: 'medium',
    notes: 'Umbrella licensing-division model; out-of-state licensees use the same application',
    locatedAt: LOCATED_AT,
  },
  id: {
    boardName: 'Idaho Physical Therapy Licensure Board (Division of Occupational and Professional Licenses)',
    boardUrl: 'https://dopl.idaho.gov/pht/',
    fees: { url: 'https://dopl.idaho.gov/wp-content/uploads/2023/06/PHT-Physical-Therapist-Application.pdf', note: 'Fees inside application packet ($50 application + $32 background check per indexed content); PDF URLs churn' },
    application: { url: 'https://dopl.idaho.gov/wp-content/uploads/2023/06/PHT-Physical-Therapist-Application.pdf', note: 'Combined packet, exam and endorsement in one form; resources at dopl.idaho.gov/pht/pht-resources/' },
    endorsement: null,
    processing: null,
    confidence: 'medium',
    notes: 'Endorsement uses the same packet as initial',
    locatedAt: LOCATED_AT,
  },
  il: {
    boardName: 'Illinois IDFPR Division of Professional Regulation — Physical Therapy Licensing and Disciplinary Board',
    boardUrl: 'https://idfpr.illinois.gov/profs/pt.html',
    fees: { url: 'https://idfpr.illinois.gov/content/dam/soi/en/web/idfpr/core/dpr/070-qualifications-for-licensure.pdf', note: "Fees/requirements in the '070 Qualifications for Licensure' document; no standalone fee page" },
    application: { url: 'https://idfpr.illinois.gov/newapplications.html', note: 'Filed via IDFPR CORE system' },
    endorsement: null,
    processing: null,
    confidence: 'medium',
    notes: 'Endorsement (10-year practice pathway) covered in the same 070 document/CORE application',
    locatedAt: LOCATED_AT,
  },
  in: {
    boardName: 'Indiana Physical Therapy Board (Indiana Professional Licensing Agency)',
    boardUrl: 'https://www.in.gov/pla/professions/physical-therapy-home/',
    fees: { url: 'https://www.in.gov/pla/professions/physical-therapy-home/physical-therapy-licensing-information/', note: '$100 application ($50 temp permit, $50 re-exam), nonrefundable; apply via MyLicense.IN.gov' },
    application: { url: 'https://www.in.gov/pla/professions/physical-therapy-board/license-information-and-application/', note: 'Initial licensure by examination' },
    endorsement: { url: 'https://www.in.gov/pla/professions/physical-therapy-board/application-by-endorsement/', note: 'Dedicated endorsement page' },
    processing: { url: 'https://www.in.gov/pla/data/', note: 'PLA interactive processing-times dashboard (days by profession) — strong rung-C wait-time source' },
    confidence: 'high',
    locatedAt: LOCATED_AT,
  },
  ia: {
    boardName: 'Iowa Board of Physical & Occupational Therapy (Dept. of Inspections, Appeals, & Licensing)',
    boardUrl: 'https://dial.iowa.gov/about-dial/boards/physical-occupational-therapy',
    fees: { url: 'https://dial.iowa.gov/licenses/health-professions/pt-ot/how-do-i-pt', note: '$120 application + $55 background check stated on apply page' },
    application: { url: 'https://dial.iowa.gov/licenses/health-professions/pt-ot/how-do-i-pt', note: "Single 'How do I' instructions page" },
    endorsement: null,
    processing: { url: 'https://dial.iowa.gov/what-expect-licensure-process', note: 'General DIAL licensure-process page (~6–8 weeks incl. FBI check per indexed content); not PT-specific' },
    confidence: 'high',
    notes: 'Endorsement handled on the same apply page',
    locatedAt: LOCATED_AT,
  },
  ks: {
    boardName: 'Kansas State Board of Healing Arts',
    boardUrl: 'https://www.ksbha.ks.gov/',
    fees: { url: 'https://www.ksbha.ks.gov/departments/licensing/license-fees', note: 'All-professions fee page (~$65 PT application + $57 fingerprints per indexed content — verify exact amounts)' },
    application: { url: 'https://www.ksbha.ks.gov/departments/licensing/licensure-types-designations/physical-therapist', note: 'Forms at ksbha.ks.gov/forms/licensing' },
    endorsement: null,
    processing: null,
    confidence: 'medium',
    notes: 'Umbrella healing-arts board; endorsement uses the same application pages',
    locatedAt: LOCATED_AT,
  },
  ky: {
    boardName: 'Kentucky Board of Physical Therapy',
    boardUrl: 'https://pt.ky.gov/',
    fees: { url: 'https://pt.ky.gov/applicants/Pages/Payment-Portal.aspx', note: 'No standalone fee page; $225 exam / $225 endorsement / $190 renewal per indexed content' },
    application: { url: 'https://pt.ky.gov/applicants/Pages/Exam-Applicants.aspx', note: 'Incl. temporary-permit supervisory agreement and KY jurisprudence exam' },
    endorsement: { url: 'https://pt.ky.gov/applicants/Pages/Endorsement-Applicants.aspx', note: 'Dedicated endorsement page' },
    processing: null,
    confidence: 'high',
    notes: 'Standalone PT board',
    locatedAt: LOCATED_AT,
  },
  la: {
    boardName: 'Louisiana Physical Therapy Board',
    boardUrl: 'https://www.laptboard.org/',
    fees: { url: 'https://www.laptboard.org/page/fees-new-applicants', note: 'New-applicant fee schedule (~$250 total incl. background check per indexed content)' },
    application: { url: 'https://www.laptboard.org/page/New-Grad-Application-Instructions', note: 'Initial/examination CAPTE-graduate instructions' },
    endorsement: { url: 'https://www.laptboard.org/page/Reciprocity-CAPTE', note: "Louisiana calls endorsement 'reciprocity'; foreign-educated variant on separate page" },
    processing: { url: 'https://www.laptboard.org/page/New-Applicant-FAQ', note: 'FAQ states issuance within 3–5 business days of complete application' },
    confidence: 'high',
    notes: 'Official state-run .org domain',
    locatedAt: LOCATED_AT,
  },
  me: {
    boardName: 'Maine Board of Examiners in Physical Therapy (Office of Professional and Occupational Regulation)',
    boardUrl: 'https://www.maine.gov/pfr/professionallicensing/professions/board-physical-therapy',
    fees: { url: 'https://www.maine.gov/pfr/professionallicensing/professions/board-physical-therapy/licensing/physical-therapist-physical-therapist-assistant', note: '$25 exam processing + $30 license + $21 background check stated on licensing page' },
    application: { url: 'https://www.maine.gov/pfr/professionallicensing/professions/board-physical-therapy/licensing/physical-therapist-physical-therapist-assistant', note: 'Exam registration via FSBPT' },
    endorsement: { url: 'https://www.maine.gov/pfr/professionallicensing/professions/board-physical-therapy/applications-forms', note: 'Applications & Forms page lists the endorsement application' },
    processing: null,
    confidence: 'high',
    locatedAt: LOCATED_AT,
  },
  md: {
    boardName: 'Maryland Board of Physical Therapy Examiners (Maryland Department of Health)',
    boardUrl: 'https://health.maryland.gov/bphte/Pages/index.aspx',
    fees: { url: 'https://health.maryland.gov/bphte/Pages/licensing.aspx', note: '$150 application per indexed content; codified at COMAR 10.38.07.02 (rung-B statutory channel)' },
    application: { url: 'https://health.maryland.gov/bphte/Pages/licensing.aspx', note: 'Online portal at mdbnc.health.maryland.gov; mandatory MD jurisprudence exam (90% pass)' },
    endorsement: null,
    processing: null,
    confidence: 'medium',
    notes: 'Endorsement uses the same portal/licensing page; only exam applicants may request a 90-day temporary license',
    locatedAt: LOCATED_AT,
  },
  ma: {
    boardName: 'Massachusetts Board of Allied Health Professions (Division of Occupational Licensure)',
    boardUrl: 'https://www.mass.gov/orgs/board-of-allied-health-professions',
    fees: { url: 'https://www.mass.gov/info-details/fees-and-license-renewal-schedules-for-allied-health-professionals', note: '$226 PT initial application; live fee table also on licensing.reg.state.ma.us' },
    application: { url: 'https://www.mass.gov/how-to/apply-for-a-license-from-the-board-of-allied-health-professionals', note: 'Filed through vendor Professional Credential Services (PCS)' },
    endorsement: null,
    processing: null,
    confidence: 'high',
    notes: 'Vendor (PCS, non-government) cites 3–4 weeks after documents received — Tier-3 contextual, not official',
    locatedAt: LOCATED_AT,
  },
  mi: {
    boardName: 'Michigan Board of Physical Therapy (LARA Bureau of Professional Licensing)',
    boardUrl: 'https://www.michigan.gov/lara/bureau-list/bpl/health/hp-lic-health-prof/pt',
    fees: { url: 'https://www.michigan.gov/lara/-/media/Project/Websites/lara/bpl/Physical-Therapy/Licensing-Info-and-Forms/Physical-Therapist-Licensing-Guide.pdf', note: 'Fees in the PT Licensing Guide PDF (~$118.95 application per indexed content); no standalone fee page' },
    application: { url: 'https://www.michigan.gov/lara/-/media/Project/Websites/lara/bpl/Physical-Therapy/Licensing-Info-and-Forms/Physical-Therapist-Licensing-Guide.pdf', note: 'Filed online via MiPLUS' },
    endorsement: { url: 'https://www.michigan.gov/-/media/Project/Websites/lara/healthsystemslicensing/Folder3/Physical_Therapy_Endorsement_app.pdf?rev=41bfc7ccadea41e285fb67372a5113ce', note: 'Endorsement instructions PDF; requires MI jurisprudence exam (75% pass)' },
    processing: null,
    confidence: 'high',
    locatedAt: LOCATED_AT,
  },
  mn: {
    boardName: 'Minnesota State Board of Physical Therapy',
    boardUrl: 'https://mn.gov/boards/physical-therapy/',
    fees: { url: 'https://mn.gov/boards/physical-therapy/applicants/applications/fees/', note: 'Dedicated fees page ($242 new-grad PT application incl. CBC and exam components)' },
    application: { url: 'https://mn.gov/boards/physical-therapy/applicants/applications/pt-license/pt-ng.jsp', note: 'New-graduate (by examination) page' },
    endorsement: { url: 'https://mn.gov/boards/physical-therapy/applicants/applications/pt-license/pt-as.jsp', note: "'PT Licensed in Another State' page" },
    processing: null,
    confidence: 'high',
    notes: 'Standalone PT board',
    locatedAt: LOCATED_AT,
  },
  ms: {
    boardName: 'Mississippi State Board of Physical Therapy',
    boardUrl: 'https://www.msbpt.ms.gov/',
    fees: { url: 'https://www.msbpt.ms.gov/sites/msbpt/files/files/Fees.pdf', note: 'Official fees document ($150 PT license, $50 fingerprint card)' },
    application: { url: 'https://www.msbpt.ms.gov/license-renewal/applying-licensure-new-graduates', note: 'New-graduates (by examination) page' },
    endorsement: { url: 'https://www.msbpt.ms.gov/license-renewal/applying-licensure-reciprocity', note: "Mississippi calls endorsement 'reciprocity'" },
    processing: null,
    confidence: 'high',
    locatedAt: LOCATED_AT,
  },
  mo: {
    boardName: 'Advisory Commission for Physical Therapists (Missouri Board of Registration for the Healing Arts)',
    boardUrl: 'https://pr.mo.gov/physicaltherapists.asp',
    fees: { url: 'https://pr.mo.gov/boards/healingarts/PT_%20Application.pdf', note: 'Fees in application instructions ($25 exam/reciprocity per indexed content); codified at 20 CSR 2150-3' },
    application: { url: 'https://pr.mo.gov/boards/healingarts/PT_%20Application.pdf', note: 'Applications reportedly moved to MOPRO online system Jan 2025 — no official MOPRO URL surfaced; re-locate during probe' },
    endorsement: null,
    processing: { url: 'https://pr.mo.gov/boards/healingarts/PT_%20Application.pdf', note: 'Instructions state minimum 6 weeks once complete; not a dashboard' },
    confidence: 'medium',
    notes: 'Site transitioning to new online system; PDF is the current anchor',
    locatedAt: LOCATED_AT,
  },
  mt: {
    boardName: 'Board of Physical, Rehabilitative, and Developmental Health Care Professionals (Montana DLI; boards consolidated Jan 2025)',
    boardUrl: 'https://boards.bsd.dli.mt.gov/physical-therapy-examiners/',
    fees: { url: 'https://boards.bsd.dli.mt.gov/physical-therapy-examiners/ptp-license-information', note: 'Fees on license-information page / application packet; set by ARM 24.177.401 (rung-B statutory channel)' },
    application: { url: 'https://boards.bsd.dli.mt.gov/physical-therapy-examiners/ptp-license-information', note: "Apply online via Citizen Portal ('New Health Care License')" },
    endorsement: null,
    processing: null,
    confidence: 'medium',
    notes: 'PT board consolidated into umbrella board effective Jan 1, 2025 (HB 438); pages still under physical-therapy-examiners path',
    locatedAt: LOCATED_AT,
  },
  ne: {
    boardName: 'Nebraska DHHS Division of Public Health, Licensure Unit (advised by the Nebraska Board of Physical Therapy)',
    boardUrl: 'https://dhhs.ne.gov/licensure/pages/physical-therapy.aspx',
    fees: { url: 'https://dhhs.ne.gov/licensure/Documents/PTInitialApplicationWCoverLtr.pdf', note: 'Fees in application packet ($133, reduced $33.25 in May–Oct of odd years, per indexed content)' },
    application: { url: 'https://dhhs.ne.gov/licensure/Documents/PTInitialApplicationWCoverLtr.pdf', note: 'Same packet covers out-of-state applicants; files closed if incomplete after 150 days' },
    endorsement: null,
    processing: null,
    confidence: 'medium',
    notes: 'Health-department model; background checks ~4–6 weeks per DHHS notes',
    locatedAt: LOCATED_AT,
  },
  nv: {
    boardName: 'Nevada Physical Therapy Board',
    boardUrl: 'https://ptboard.nv.gov/',
    fees: { url: 'https://ptboard.nv.gov/Licensure/Fee_Schedule/', note: 'Dedicated fee schedule ($300 PT application + $39 fingerprints + $25 exam processing)' },
    application: { url: 'https://ptboard.nv.gov/Applicants/Home-NewApplicants/', note: 'Exam Candidate Application Guide PDF linked from page' },
    endorsement: { url: 'https://ptboard.nv.gov/uploadedFiles/ptboardnvgov/content/Applicants/EndorsementCandidate2024%20-%20Copy.pdf', note: 'Endorsement Candidate Application Guide' },
    processing: { url: 'https://ptboard.nv.gov/uploadedFiles/ptboardnvgov/content/Applicants/EndorsementCandidate2024%20-%20Copy.pdf', note: 'Guides state ~3–4 weeks (e-fingerprints) to ~6–8 weeks (hard card); not a dashboard' },
    confidence: 'high',
    notes: 'ACTIVE PT Compact member — began issuing privileges Jan 20, 2026; incoming privilege holders must pass the NVJAM jurisprudence exam (board compact page: ptboard.nv.gov/Applicants/physical-therapy-compact/)',
    locatedAt: LOCATED_AT,
  },
  nh: {
    boardName: 'Physical Therapy Governing Board (NH Office of Professional Licensure and Certification)',
    boardUrl: 'https://www.oplc.nh.gov/find-board/physical-therapy-governing-board',
    fees: { url: 'https://www.oplc.nh.gov/find-board/physical-therapy-governing-board/physical-therapy-license-fees', note: 'Dedicated fees page ($121 application/renewal/reinstatement)' },
    application: { url: 'https://www.oplc.nh.gov/find-board/physical-therapy-governing-board/physical-therapy-applications', note: 'Single applications page covers all pathways' },
    endorsement: null,
    processing: null,
    confidence: 'high',
    notes: 'OPLC umbrella model; temporary licenses issued in 24–48 business hours per OPLC guidance',
    locatedAt: LOCATED_AT,
  },
  nj: {
    boardName: 'New Jersey State Board of Physical Therapy Examiners (Division of Consumer Affairs)',
    boardUrl: 'https://www.njconsumeraffairs.gov/pt',
    fees: { url: 'https://www.njconsumeraffairs.gov/Documents/licenseprocess/Physical-Therapy-Helpful-Information-Regarding-the-Application-Process.pdf', note: 'Fees in application-process document ($125 application; $110/$55 initial license by cycle year)' },
    application: { url: 'https://www.njconsumeraffairs.gov/pt/pages/applications.aspx', note: 'Online filing via Division licensing portal' },
    endorsement: null,
    processing: null,
    confidence: 'medium',
    notes: 'Consumer-affairs-division model',
    locatedAt: LOCATED_AT,
  },
  nm: {
    boardName: 'New Mexico Physical Therapy Board (Regulation and Licensing Department)',
    boardUrl: 'https://www.rld.nm.gov/boards-and-commissions/individual-boards-and-commissions/physical-therapy/',
    fees: { url: 'https://www.rld.nm.gov/boards-and-commissions/individual-boards-and-commissions/physical-therapy/fees/', note: 'Dedicated fees page ($160 PT full licensure); codified at 16.20.5.8 NMAC (rung-B statutory channel)' },
    application: { url: 'https://www.rld.nm.gov/boards-and-commissions/individual-boards-and-commissions/physical-therapy/licensing-registration-and-renewal/', note: 'Incl. NM jurisprudence exam and DPS background form' },
    endorsement: null,
    processing: null,
    confidence: 'high',
    notes: 'Expedited licensure for holders of valid unrestricted out-of-state licenses (16.7.8 NMAC)',
    locatedAt: LOCATED_AT,
  },
  nc: {
    boardName: 'North Carolina Board of Physical Therapy Examiners',
    boardUrl: 'https://www.ncptboard.org/',
    fees: { url: 'https://www2.ncptboard.org/app/Licensing/ScheduleOfFees.php', note: 'Dedicated fee schedule on the www2 application subdomain' },
    application: { url: 'https://www2.ncptboard.org/app/Licensing/ApplicationInstructions.php', note: 'Single instructions page for all applicant types; online application on same subdomain' },
    endorsement: null,
    processing: null,
    confidence: 'high',
    notes: 'Standalone board on state-sanctioned domain; ~10 business days once complete circulates but unattributed to an official page',
    locatedAt: LOCATED_AT,
  },
  nd: {
    boardName: 'North Dakota Board of Physical Therapy',
    boardUrl: 'https://www.ndbpt.org/',
    fees: { url: 'https://www.ndbpt.org/apply/pt_licensure.asp', note: 'Fees in application instructions ($200 application + ~$41.25 background check per indexed content)' },
    application: { url: 'https://www.ndbpt.org/apply/pt_licensure.asp', note: 'Initial application instructions; foreign-trained variant on separate page' },
    endorsement: null,
    processing: null,
    confidence: 'high',
    notes: 'Standalone board; endorsement uses the same online application',
    locatedAt: LOCATED_AT,
  },
  oh: {
    boardName: 'Ohio Occupational Therapy, Physical Therapy, and Athletic Trainers (OTPTAT) Board',
    boardUrl: 'https://otptat.ohio.gov/',
    fees: { url: 'https://otptat.ohio.gov/physical-therapy/licensing', note: '$100 application (exam and endorsement) via eLicense Ohio; fee rule OAC 4755-24-03 (rung-B statutory channel)' },
    application: { url: 'https://otptat.ohio.gov/physical-therapy/licensing/pt-examination-application', note: 'Apply via elicense.ohio.gov' },
    endorsement: { url: 'https://otptat.ohio.gov/physical-therapy/licensing', note: 'Dedicated endorsement page exists but exact URL did not surface — locate during probe' },
    processing: null,
    confidence: 'medium',
    notes: 'Applications reviewed within 5 business days of submission per application pages',
    locatedAt: LOCATED_AT,
  },
  ok: {
    boardName: 'Oklahoma State Board of Medical Licensure and Supervision (PT Advisory Committee)',
    boardUrl: 'https://www.okmedicalboard.org/',
    fees: { url: 'https://www.okmedicalboard.org/physical_therapists/download/220/PT+Instructions_102025.pdf', note: 'Fees in instructions PDF (Oct 2025); paid via pay.apps.ok.gov' },
    application: { url: 'https://www.okmedicalboard.org/physical_therapists', note: 'Applications must arrive 30+ days before a PT Advisory Committee meeting' },
    endorsement: null,
    processing: null,
    confidence: 'medium',
    notes: 'PT licensing under the state medical board; committee-meeting cadence drives timing',
    locatedAt: LOCATED_AT,
  },
  or: {
    boardName: 'Oregon Board of Physical Therapy',
    boardUrl: 'https://www.oregon.gov/pt/pages/default.aspx',
    fees: { url: 'https://www.oregon.gov/pt/pages/apply.aspx', note: 'Fees collected in Applicant Portal; set by OAR 848-005-0020 ($150 exam application, $50 compact privilege) — rung-B statutory channel via secure.sos.state.or.us' },
    application: { url: 'https://www.oregon.gov/pt/pages/apply.aspx', note: 'Single applying-for-licensure page covers exam and endorsement' },
    endorsement: null,
    processing: null,
    confidence: 'high',
    locatedAt: LOCATED_AT,
  },
  pa: {
    boardName: 'Pennsylvania State Board of Physical Therapy (Department of State, BPOA)',
    boardUrl: 'https://www.pa.gov/agencies/dos/department-and-offices/bpoa/boards-commissions/physical-therapy',
    fees: { url: 'https://www.pacodeandbulletin.gov/Display/pacode?file=/secure/pacode/data/049/chapter40/s40.5.html&d=reduce', note: '49 Pa. Code § 40.5: $30 exam/endorsement application, $90 biennial renewal — rung-B statutory channel' },
    application: { url: 'https://www.pa.gov/agencies/dos/department-and-offices/bpoa/boards-commissions/physical-therapy/physical-therapist-licensure-snapshot', note: 'Licensure snapshot; apply via pals.pa.gov' },
    endorsement: null,
    processing: { url: 'https://www.pa.gov/agencies/dos/resources/professional-licensing-resources/licensure-processing-guides-and-timelines', note: 'Official BPOA processing guides/timelines page (all DOS boards, phase-based); not PT-specific' },
    confidence: 'high',
    locatedAt: LOCATED_AT,
  },
  ri: {
    boardName: 'Rhode Island Department of Health — Board of Physical Therapy',
    boardUrl: 'https://health.ri.gov/physical-therapists',
    fees: { url: 'https://health.ri.gov/sites/g/files/xkgbur1006/files/applications/PhysicalTherapist.pdf', note: '$155 application fee stated on the application form PDF' },
    application: { url: 'https://health.ri.gov/physical-therapists', note: 'Regulations at 216-RICR-40-05-13' },
    endorsement: null,
    processing: { url: 'https://health.ri.gov/sites/g/files/xkgbur1006/files/forms/faqs/MyLicenseFAQs.pdf', note: 'RIDOH-wide FAQ: ~6–8 weeks initial, ~5 business days renewals; not PT-specific' },
    confidence: 'medium',
    notes: 'Umbrella health-department model',
    locatedAt: LOCATED_AT,
  },
  sc: {
    boardName: 'South Carolina Board of Physical Therapy Examiners (LLR)',
    boardUrl: 'https://llr.sc.gov/pt/',
    fees: { url: 'https://www.llr.sc.gov/pt/fees.aspx', note: 'Dedicated fees page ($110 PT initial application per indexed content)' },
    application: { url: 'https://llr.sc.gov/pt/exam.aspx', note: 'Licensure-by-examination page; electronic application' },
    endorsement: { url: 'https://www.llr.sc.gov/pt/endorsement.aspx', note: 'Dedicated endorsement page' },
    processing: null,
    confidence: 'high',
    notes: 'LLR umbrella licensing agency',
    locatedAt: LOCATED_AT,
  },
  sd: {
    boardName: 'South Dakota Board of Physical Therapy (SD Department of Health)',
    boardUrl: 'https://doh.sd.gov/licensing-and-records/boards/physical-therapy/',
    fees: { url: 'https://doh.sd.gov/licensing-and-records/boards/physical-therapy/licensing-requirements/', note: 'Fees in requirements/application materials (~$120 per indexed content, unverified on-page)' },
    application: { url: 'https://doh.sd.gov/licensing-and-records/boards/physical-therapy/licensing-requirements/', note: 'Forms on separate board forms page' },
    endorsement: null,
    processing: null,
    confidence: 'medium',
    notes: 'PT licensure moved from the medical board (sdbmoe.gov) to this new DOH board July 1, 2023 — do not use the old domain',
    locatedAt: LOCATED_AT,
  },
  tn: {
    boardName: 'Tennessee Board of Physical Therapy (TN Department of Health)',
    boardUrl: 'https://www.tn.gov/health/licensure/pt.html',
    fees: { url: 'https://www.tn.gov/health/health-program-areas/health-professional-boards/pt-board/pt-board/licensure.html', note: 'Fees set by rule 1150-01-.06; dollar amounts not confirmed via index — verify during probe' },
    application: { url: 'https://www.tn.gov/health/health-program-areas/health-professional-boards/pt-board/pt-board/licensure.html', note: 'Apply via TDH LARS system; requires notarized citizenship declaration and direct transcript' },
    endorsement: null,
    processing: null,
    confidence: 'medium',
    notes: 'Umbrella health-department boards model',
    locatedAt: LOCATED_AT,
  },
  ut: {
    boardName: 'Utah Division of Professional Licensing (DOPL) — Physical Therapy Licensing Board',
    boardUrl: 'https://dopl.utah.gov/physical-therapy/',
    fees: { url: 'https://dopl.utah.gov/wp-content/uploads/2022/11/fee-schedule.pdf', note: 'DOPL all-professions fee schedule PDF; PDF URLs churn' },
    application: { url: 'https://dopl.utah.gov/physical-therapy/apply-for-a-license/physical-therapist/', note: 'Covers exam and endorsement; separate exam-approval page exists' },
    endorsement: null,
    processing: null,
    confidence: 'high',
    notes: 'DOPL publishes processing times for some professions but not PT',
    locatedAt: LOCATED_AT,
  },
  vt: {
    boardName: 'Vermont Secretary of State, Office of Professional Regulation — Physical Therapists',
    boardUrl: 'https://sos.vermont.gov/physical-therapists',
    fees: { url: 'https://outside.vermont.gov/dept/sos/office_professional_regulation/general/initial_licensing_renewal_fees_dates_90-day_licensing_policy.pdf', note: 'OPR fees & dates PDF ($115 PT application per indexed content); fees set in statute' },
    application: { url: 'https://sos.vermont.gov/physical-therapists/forms-instructions', note: 'Forms & instructions page' },
    endorsement: null,
    processing: { url: 'https://outside.vermont.gov/dept/sos/office_professional_regulation/general/initial_licensing_renewal_fees_dates_90-day_licensing_policy.pdf', note: "OPR '90-day initial licensing policy' in the same PDF; not a dashboard" },
    confidence: 'high',
    notes: 'Advisor-profession model under Secretary of State OPR; compact live Mar 1, 2025',
    locatedAt: LOCATED_AT,
  },
  va: {
    boardName: 'Virginia Board of Physical Therapy (Department of Health Professions)',
    boardUrl: 'https://www.dhp.virginia.gov/Boards/PhysicalTherapy/',
    fees: { url: 'https://law.lis.virginia.gov/admincode/title18/agency112/chapter20/section27/', note: '18VAC112-20-27: $140 PT application (exam or endorsement) — rung-B statutory channel on law.lis.virginia.gov' },
    application: { url: 'https://www.license.dhp.virginia.gov/apply/Forms/PhysicalTherapy/PT_Exam_instruct_form.pdf', note: 'Exam application instructions (rev. 09/2025); forms hub on dhp.virginia.gov' },
    endorsement: { url: 'https://www.license.dhp.virginia.gov/apply/Forms/PhysicalTherapy/PT_End_instruct.pdf', note: 'Endorsement instructions (rev. 09/2025)' },
    processing: null,
    confidence: 'high',
    locatedAt: LOCATED_AT,
  },
  wa: {
    boardName: 'Washington State Department of Health — Board of Physical Therapy',
    boardUrl: 'https://doh.wa.gov/licenses-permits-and-certificates/professions-new-renew-or-update/physical-therapist-and-physical-therapist-assistant',
    fees: { url: 'https://doh.wa.gov/licenses-permits-and-certificates/professions-new-renew-or-update/physical-therapist-and-physical-therapist-assistant/fees', note: 'Dedicated PT/PTA fees page' },
    application: { url: 'https://doh.wa.gov/licenses-permits-and-certificates/professions-new-renew-or-update/physical-therapist-and-physical-therapist-assistant/licensing-requirements', note: 'Incl. WA jurisprudence exam' },
    endorsement: { url: 'https://doh.wa.gov/licenses-permits-and-certificates/professions-new-renew-or-update/physical-therapist-and-physical-therapist-assistant/substantially-equivalent-states', note: 'Endorsement pathway effective Jan 1, 2026 for board-approved substantially-equivalent states (all 50 + DC approved)' },
    processing: { url: 'https://doh.wa.gov/licenses-permits-and-certificates/professions-new-renew-or-update/application-status', note: 'DOH application-status page with published timeline guidance — strong rung-C wait-time source' },
    confidence: 'high',
    notes: 'Umbrella DOH with appointed PT board; compact member',
    locatedAt: LOCATED_AT,
  },
  wv: {
    boardName: 'West Virginia Board of Physical Therapy',
    boardUrl: 'https://wvbopt.wv.gov/',
    fees: null, // fees paid through the online portal after submission; fee-waiver page exists
    application: { url: 'https://wvbopt.wv.gov/pt-pta/Pages/Applications.aspx', note: 'Exam, endorsement, and foreign-trained applications all on this page' },
    endorsement: null,
    processing: null,
    confidence: 'high',
    notes: 'Standalone board (also regulates athletic trainers); no public fee schedule found',
    locatedAt: LOCATED_AT,
  },
  wi: {
    boardName: 'Wisconsin Physical Therapy Examining Board (DSPS)',
    boardUrl: 'https://dsps.wi.gov/Pages/BoardsCouncils/PT/Default.aspx',
    fees: { url: 'https://dsps.wi.gov/Credentialing/Health/info3195.pdf', note: 'Credentialing doc #3195 ($68 initial credential per indexed content); renewal fees in separate DSPS PDF' },
    application: { url: 'https://dsps.wi.gov/Pages/Professions/PT/Default.aspx', note: 'Incl. Wisconsin statutes open-book exam; filed via LicensE portal' },
    endorsement: null,
    processing: null,
    confidence: 'medium',
    notes: 'DSPS provides per-applicant status lookup only, no published processing times',
    locatedAt: LOCATED_AT,
  },
  wy: {
    boardName: 'Wyoming Board of Physical Therapy',
    boardUrl: 'https://physicaltherapy.wyo.gov/',
    fees: { url: 'https://physicaltherapy.wyo.gov/forms', note: 'Fees with application materials ($50 application, $190 annual renewal per indexed content)' },
    application: { url: 'https://physicaltherapy.wyo.gov/forms', note: 'Forms page for PT/PTA licensure' },
    endorsement: null,
    processing: null,
    confidence: 'medium',
    notes: 'Indexed snippets cite 5–7 business days processing + 4–6 weeks background checks but hosting page unconfirmed — locate during probe',
    locatedAt: LOCATED_AT,
  },
  pr: {
    boardName: 'Junta Examinadora de Terapia Física de Puerto Rico (Departamento de Salud, ORCPS)',
    boardUrl: 'https://www.salud.pr.gov/CMS/488',
    fees: { url: 'https://www.salud.pr.gov/CMS/DOWNLOAD/6436', note: 'Statutory fees per Ley 114 de 1962 ($25 with exam per indexed content); no modern fee page' },
    application: { url: 'https://www.salud.pr.gov/CMS/488', note: 'Board hub page; online services via orcps.salud.pr.gov' },
    endorsement: null,
    processing: null,
    confidence: 'medium',
    notes: 'Thin web presence; Ley 102-2025 (universal license recognition) now governs out-of-jurisdiction recognition — verify during seeding',
    locatedAt: LOCATED_AT,
  },
  vi: {
    boardName: 'Virgin Islands Board of Physical Therapy (VI Department of Health)',
    boardUrl: 'https://www.vitherapyboard.org/',
    fees: { url: 'https://www.vitherapyboard.org/applications-forms/new-applicants/', note: '$15 application + $200 PT registration stated with application materials' },
    application: { url: 'https://www.vitherapyboard.org/applications-forms/new-applicants/', note: 'Single new-applicant pathway covers out-of-state licensees' },
    endorsement: null,
    processing: null,
    confidence: 'medium',
    notes: "Board's own site is .org (not .gov) but is the official board presence, listed by FSBPT; thin web presence overall",
    locatedAt: LOCATED_AT,
  },
};
